### ISSUE TITLE
Image not loading if there is any special character in caption in the captioning demo

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/Grad-CAM#12]
If I enter any special character in the caption input field, then the image generated is not rendered. need to encode the the image url at the backend before rendering it at the frontend. 

For reference, see this http://stackoverflow.com/questions/5607551/how-to-urlencode-a-querystring-in-python

**Comment by RishabhJain2018** [comment]
@deshraj Can I fix this??

**Comment by deshraj** [comment]
Sure.

**Comment by KrUciFieR-Jr** [comment]
Is this still open? If yes Can I work on it?

**Comment by RishabhJain2018** [comment]
@KrUciFieR-Jr Yes, this is fixed. Only PR needs to be merged :sweat_smile: . I suggest you to take a look on our GSoC projects http://gsoc.cloudcv.org/ and take up a issue from them. Please feel free to ask, if you have doubts.

**Comment by KrUciFieR-Jr** [comment]
Yes, Thank You @RishabhJain2018 Looking forward to work with you guys
