### ISSUE TITLE
Add capability to upload images using URLs

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/Grad-CAM#9]
For now, one can upload images by choosing one image from their computer. We want the user to upload the image using an image URL.

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by deshraj** [comment]
Sure. No one is assigned to this issue. You can work on this. :-)

**Comment by RishabhJain2018** [comment]
ok. :)

**Comment by deshraj** [comment]
Can you also work on this issue https://github.com/Cloud-CV/diverse-beam-search/issues/1

Both the issues are almost similar.

**Comment by RishabhJain2018** [comment]
yeah sure. I will fix both of them.

**Comment by RishabhJain2018** [comment]
@deshraj What should be the directory name in which the images on the server will be downloaded?

**Comment by deshraj** [comment]
@RishabhJain2018 can you see this https://github.com/Cloud-CV/Grad-CAM/blob/master/grad_cam/views.py#L106

Currently, the image is uploaded in the `output_dir` and you should also aim to store the image in this folder only.

**Comment by RishabhJain2018** [comment]
okk sure.

**Comment by deshraj** [comment]
Fixed in #11
